version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: sql_server
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./dbData:/var/lib/mysql
    networks:
      - leed_network

  apache:
    build: ./dockerFiles/apache
    container_name: web_server
    ports: 
      - "${APACHE_PORT}:80"
    networks:
      - leed_network
    depends_on:
      - mysql
  
  config:
    build: ./dockerFiles/autoConfig
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APACHE_PORT: ${APACHE_PORT}
      MYSQL_PORT: ${MYSQL_PORT}
      AUTO_EXECUTE_CONFIG: ${AUTO_EXECUTE_CONFIG}
      RETRY_TIMEOUT_COUNT: ${RETRY_TIMEOUT_COUNT}
    networks:
      - leed_network
    depends_on:
      - apache


networks:
  leed_network:
    driver: bridge